print("!Hola mundo!")
print("Hola de nuevo")
print("Me encanta escribir esto.")
print("Esto es divertido.")
print('¡Sí! Imprimiendo.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')

print("Esto es muy sencillo")
# print("Esto no se imprimirá")